version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 1323:1323
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    ports:
      - 3307:3307